### ISSUE TITLE
Udpate DT?

### ISSUE THREAD

**Issue by TheNickoos** [PrincessRTFM/TinyCommands#12]
Just asking if it going to happen?

**Comment by PrincessRTFM** [comment]
I'd love to, but the XivCommon library that I use to send commands to the game isn't updated. Without that, things like the conditional commands and the `/delay` command don't work, and the plugin won't even compile with the old version.

**Comment by Gnostars** [comment]
i was refraining from opening an issue here to ask, but i see now that I wasn't the only one who deeply missed TinyCommands... I used the conditional commands to customize emotes based on target and had some really neat ones.... Plus the tremendous utilities for more productive activities. 
Are there any current known plans for XivCommon to update for DT? I checked the repo, but the last update was last month. That gives me hope, but I would rather not bug or rush anyone to do something they're already doing for free.

**Comment by Nox13last** [comment]
I also tend to refrain from "when plogon upd8?", but I'd like to also register my interest in the subject.

There's are emotes for _/draw_ and _/sheathe_, where you do it with a bit of flourish, but those emotes don't care if the weapon is already in a given state (you can _/draw_ if your weapon is already drawn, and it animates jarringly).
TinyCommands at least let me make a button with "If sheathed, then _/draw_. If drawn, then _/sheathe_".

**Comment by PrincessRTFM** [comment]
Unfortunately, XivCommon's author isn't in the Dalamud discord, so I have no ETA on when she'll update the library. I don't even know _if_ she will, I'm just hoping. I'll see if maybe I can set up a (temporary) build that works without it, but no promises.

As for the `/draw` and `/sheathe` emotes, you may be interested in [WoLua](https://github.com/PrincessRTFM/WoLua) (once it's back - also reliant on XivCommon) and the [_battlemode_ script](https://github.com/PrincessRTFM/WoLua.battlemode) (also my own work) for it. It does basically what you've described, only with more advanced checks, making it useful as a drop-in replacement for the normal draw/sheathe keybind.

**Comment by Nox13last** [comment]
Aw hell yeah. I remember talking to you in a previous ticket about WoLua. I never got around to figuring it out. Guess I should start.

Looking forward to both TC **and** WoLua now.

**Comment by PrincessRTFM** [comment]
Good news! I was able to make a (temporary) replacement for XivCommon, since the feature I need was apparently just a single file.
