### ISSUE TITLE
7.11 Update?

### ISSUE THREAD

**Issue by Valgrifer** [PrincessRTFM/TinyCommands#15]
Can you update for patch 7.11?

**Comment by AetherCollective** [comment]
The latest commit works with 7.11. If you build it with Visual Studios, and bump the DalamudApiLevel up to 11 in the json file, you can load it as a dev plugin.

**Comment by PrincessRTFM** [comment]
It's worth noting that I'm not actually playing the game, but it compiled so it's probably fine

**Comment by AetherCollective** [comment]
I've been using it for a while (bout a week). I haven't seen any problems with it
