### ISSUE TITLE
Add Weapon Out flag for /ifcmd?

### ISSUE THREAD

**Issue by Grammernatzi** [PrincessRTFM/TinyCommands#4]
I already added this in a version I built myself of the plugin, using this: 

```
else if (flags["z"] && !TinyCmds.client.LocalPlayer.StatusFlags.HasFlag(StatusFlags.WeaponOut))
	msg = "Weapon is not out";
else if (flags["Z"] && TinyCmds.client.LocalPlayer.StatusFlags.HasFlag(StatusFlags.WeaponOut))
        msg = "Weapon is out";
```

It would be neat to have it in the main plugin, though. With /draw and /sheathe now being a thing, I used it to make a fancy draw/sheath macro, which works well with this code.

**Comment by PrincessRTFM** [comment]
As the commit message mentions, I used `-r` for the flag. Mnemonic is that you're **r**eady to fight if your weapon is out.

**Comment by Grammernatzi** [comment]
Makes sense. I just did it as -z because that was the default keybind for draw/sheath and that's what stuck in my head, but -r makes more sense as mnemonic.
