### ISSUE TITLE
Inability to Update/Install Tinycmd

### ISSUE THREAD

**Issue by iRobsie** [PrincessRTFM/TinyCommands#8]
Have been unable to install since it appeared for update. I've completely wiped all of it's saved data everywhere I could find but I receive the similar/same error messages on install.

> 09:52:07.087 | INF [LOCALPLUGIN] Loading TinyCmds.dll
> 09:52:07.184 | INF [TinyCmds] [09:52:07.184/.NET ThreadPool Worker#42] PlaySound loaded; address = 0x00007FF71BF25FD0, base memory offset = 0x00000000000A5FD0
> 09:52:07.198 | ERR [LOCALPLUGIN] Error while loading TinyCommands
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
> Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
>    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    at System.Reflection.Assembly.GetTypes()
>    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
>    at PrincessRTFM.TinyCmds.PluginCommandManager..ctor(Plugin core)
>    at PrincessRTFM.TinyCmds.Plugin..ctor() in D:\a\TinyCommands\TinyCommands\TinyCmds\Plugin.cs:line 58
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> File name: 'Microsoft.EntityFrameworkCore, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
>  ---> System.NotSupportedException: Resolving to a collectible assembly is not supported.
> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> File name: 'Microsoft.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
>  ---> System.NotSupportedException: Resolving to a collectible assembly is not supported.
> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> File name: 'Microsoft.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
>  ---> System.NotSupportedException: Resolving to a collectible assembly is not supported.
> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> File name: 'Microsoft.EntityFrameworkCore, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
>  ---> System.NotSupportedException: Resolving to a collectible assembly is not supported.
>    --- End of inner exception stack trace ---
>    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 107
>    at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 456
> 09:52:07.199 | ERR [PLUGINW] Plugin installer threw an unexpected error
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
> Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
>    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    at System.Reflection.Assembly.GetTypes()
>    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
>    at PrincessRTFM.TinyCmds.PluginCommandManager..ctor(Plugin core)
>    at PrincessRTFM.TinyCmds.Plugin..ctor() in D:\a\TinyCommands\TinyCommands\TinyCmds\Plugin.cs:line 58
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> File name: 'Microsoft.EntityFrameworkCore, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
>  ---> System.NotSupportedException: Resolving to a collectible assembly is not supported.
> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> File name: 'Microsoft.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
>  ---> System.NotSupportedException: Resolving to a collectible assembly is not supported.
> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> File name: 'Microsoft.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
>  ---> System.NotSupportedException: Resolving to a collectible assembly is not supported.
> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Operation is not supported. (0x80131515)
> File name: 'Microsoft.EntityFrameworkCore, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
>  ---> System.NotSupportedException: Resolving to a collectible assembly is not supported.
>    --- End of inner exception stack trace ---
>    at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 107
>    at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 456
>    at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 946
>    at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 826

**Comment by PrincessRTFM** [comment]
Hoo fuckin boy. I just loaded up my own dev copy to test it and got an error a mile long. Tracked it down fast though, I know exactly what seems to have gone wrong. Fix is like two lines, gimme a sec to push the update.

**Comment by PrincessRTFM** [comment]
Okay, github's having some issues and the build/deploy process can't run while their servers are chugging this bad, so I'm afraid you're gonna have to wait a little longer before I can get the update actually live.

**Comment by PrincessRTFM** [comment]
It's deploying now, give it a few minutes and it'll be live
